### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by aseemk** [typefoo/node-shopify#4]
Hi there,

Great work on the library. =) What license is it under though?

If you're unsure, GitHub has published a nice website to help pick:

http://choosealicense.com/

Thanks!

**Comment by jjosef** [comment]
Hey @aseemk, it is MIT licensed. We will add a LICENSE file.

**Comment by aseemk** [comment]
Great, thanks!

**Comment by jjosef** [comment]
License added in v0.2.3
